In [1]:
import tensorflow as tf

# Defining two vectors of length 3
vector1 = tf.constant([1, 2, 3], dtype=tf.float32)
vector2 = tf.constant([4, 5, 6], dtype=tf.float32)

# Calculating the dot product
dot_product = tf.reduce_sum(tf.multiply(vector1, vector2))

print("Dot Product:", dot_product.numpy())


Dot Product: 32.0


In [2]:
# Define two matrices of size (2, 2)
matrix1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
matrix2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Perform matrix multiplication
result_matrix = tf.linalg.matmul(matrix1, matrix2)

print("Matrix 1:")
print(matrix1.numpy())

print("Matrix 2:")
print(matrix2.numpy())

print("Resultant Matrix (Matrix Multiplication):")
print(result_matrix.numpy())

Matrix 1:
[[1. 2.]
 [3. 4.]]
Matrix 2:
[[5. 6.]
 [7. 8.]]
Resultant Matrix (Matrix Multiplication):
[[19. 22.]
 [43. 50.]]
