In [6]:
import torch

# Defining two vectors of length 3
vector1 = torch.tensor([1, 2, 3], dtype=torch.float32)
vector2 = torch.tensor([4, 5, 6], dtype=torch.float32)

# Calculating the dot product
dot_product = torch.dot(vector1, vector2)

print("Dot Product:", dot_product.item())


Dot Product: 32.0


In [7]:
# defining 2 matrixs of size(2,2)
matrix1 = torch.tensor([[1, 2,], [3, 4]], dtype=torch.float32)
print("Matrix 1:")
print(matrix1)

print("\n")

matrix2 = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print("Matrix 2:")
print(matrix2)

print("\n")

# Performing matrix multiplication using PyTorch
multiplication = torch.matmul(matrix1, matrix2)
print("Resultant Matrix (Matrix Multiplication):")
print(multiplication)

Matrix 1:
tensor([[1., 2.],
        [3., 4.]])


Matrix 2:
tensor([[5., 6.],
        [7., 8.]])


Resultant Matrix (Matrix Multiplication):
tensor([[19., 22.],
        [43., 50.]])
